import { User } from '@phosphor-icons/react';
import Head from 'next/head';
import { useState } from 'react';

import Layout from "@/Layout";

import { theme } from '@/styles/stitches.config';

import { Header } from './styles';

export default function Profile() {
    const { colors } = theme;

    const [filterSelected, setFilterSelected] = useState('');

    return (
        <>
            <Head>
                <title>Profile | Book Wise</title>

                <meta name="description" content="Generated by create next app" />

                <meta name="viewport" content="width=device-width, initial-scale=1" />

                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Layout title='Profile' icon={<User size={32} color={colors.green100.value} />}>
                {/* Header */}
                <Header>
                    <User size={32} color={colors.green100.value} />

                    <h1>Profile</h1>
                </Header>

                {/* Cards */}
                {/* <Container>
                    <Content>
                        <Search>
                            <SearchInput placeholder='Buscar livro ou autor' />
                        </Search>

                        <ExplorerBooks>
                            {recentReviews.map(pub => (
                                <BookCardReduce key={pub.id} book={pub.book} />
                            ))}
                        </ExplorerBooks>
                    </Content>

                    <Aside>
                        <UserComponent />
                    </Aside>
                </Container> */}
            </Layout>

        </>
    )
}