import { ChartLine } from '@phosphor-icons/react';
import { useSession } from 'next-auth/react';
import Head from 'next/head';

import Layout from '@/components/Layout';

import { theme } from '@/styles/stitches.config';

import { LatestLibrary } from './components/LatestLibrary';
import { PopularLibrary } from './components/PopularLibrary';
import { ReadingList } from './components/ReadingList';

import { books, recentReviews } from './utils/book';

import { Aside, Center, Container, Header } from './styles';

export default function Home() {
    const { colors } = theme

    const { data } = useSession();
    console.log(data)

    return (
        <>
            <Head>
                <title>Home | Book Wise</title>

                <meta name="description" content="Generated by create next app" />

                <meta name="viewport" content="width=device-width, initial-scale=1" />

                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Layout>
                <Header>
                    <ChartLine size={32} color={colors.green100.value} />

                    <h1>Início</h1>
                </Header>

                <Container>
                    <Center>
                        {data?.user && (
                            <ReadingList
                                title="Sua última leitura"
                                urlReference="/"
                                books={[books[0]]}
                            />
                        )}

                        <LatestLibrary
                            title="Avaliações mais recentes"
                            publication={recentReviews}
                        />
                    </Center>

                    <Aside>
                        <PopularLibrary
                            title="Livros populares"
                            urlReference="/"
                            books={books}
                        />
                    </Aside>
                </Container>
            </Layout>
        </>
    )
}