import { ChartLine } from '@phosphor-icons/react';
import { useSession } from 'next-auth/react';
import Head from 'next/head';

import { Card } from '@/components/Card';
import { Navbar } from '@/components/Navbar';

import { theme } from '@/styles/stitches.config';

import { BooksContent, Container, Content } from './styles';

export default function Home() {
    const { colors } = theme

    const session = useSession();

    console.log(session)

    return (
        <>
            <Head>
                <title>Home | Book Wise</title>

                <meta name="description" content="Generated by create next app" />

                <meta name="viewport" content="width=device-width, initial-scale=1" />

                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Container>
                <Navbar />

                <Content>
                    <div className="header">
                        <ChartLine size={32} color={colors.green100.value} />

                        <h2>Início</h2>
                    </div>

                    <div className='sections'>
                        <BooksContent>
                            <h6>Avaliações mais recentes</h6>

                            <Card />

                            <Card />

                            <Card />
                        </BooksContent>

                        {/* <Aside>
                            <div className="header">
                                <h5>Livros populares</h5>

                                <Link href="/">Ver todos</Link>
                            </div>

                            <ShyCard />

                            <ShyCard />

                            <ShyCard />
                        </Aside> */}
                    </div>
                </Content>
            </Container>
        </>
    )
}